const quiz=[
{question:"Q1. What makes consumers feel most rewarded today?",answers:["Earning more points","Bigger cashback percentages","Relevant offers at the right moment","Luxury reward catalogues"],correct:2,reveal:"Consumers increasingly value relevance and immediacy over accumulating rewards they'll redeem later. Loyalty is shifting from rewards programs to engagement ecosystems."},
{question:"Q2. Which is hardest for issuers to build themselves?",answers:["Campaign reporting","A scaled merchant offer ecosystem","Points management","Customer communications"],correct:1,reveal:"Building and maintaining thousands of merchant relationships and offers at scale requires a large ecosystem and continuous content refresh."},
{question:"Q3. Which statement is most likely to be true in 2030?",answers:["Loyalty will become increasingly invisible and embedded","Cashback will replace loyalty programs","Points will disappear","Consumers will join fewer programs"],correct:0,reveal:"Loyalty is evolving from standalone rewards programs to always-on engagement embedded across everyday experiences, moving from cost to a monetisation driver."},
{question:"Q4. What is Visa AP's newest consumer platform?",answers:["visa.com.sg","linkedin.com/visa","instagram.com/visaasiapacific","my.visa.com"],correct:3,reveal:"my.visa.com is Visa's latest one-stop destination for card benefits, offers, sponsorships and campaigns. Open to Visa employees now, launching publicly in early July."},
{question:"Q5. What is Vee's favourite colour?",answers:["Royal blue","Glittery pink","Warm gold","Ivory white"],correct:1,reveal:"Vee bleeds Visa blue, but secretly loves glittery pink!!!"}
];
const stampLabels={quiz:"Quiz Master",video:"Watch Video",vee:"Found VEE"};
let participantName="",currentQuestion=0,correctCount=0,challengeStartTime=null,challengeEndTime=null,timerInterval=null,cameraStream=null,challengeCompleted=false,nextAfterStamp="passportAfterQuiz";
const stamps={quiz:false,video:false,vee:false};
const $=id=>document.getElementById(id);
const homeScreen=$("homeScreen"),passportIntroScreen=$("passportIntroScreen"),countdownScreen=$("countdownScreen"),quizScreen=$("quizScreen"),stampScreen=$("stampScreen"),passportProgressScreen=$("passportProgressScreen"),videoScreen=$("videoScreen"),cameraIntroScreen=$("cameraIntroScreen"),cameraScreen=$("cameraScreen"),completeScreen=$("completeScreen");
const startBtn=$("startBtn"),beginQuizBtn=$("beginQuizBtn"),participantInput=$("participantName"),nameError=$("nameError"),countdownNumber=$("countdownNumber"),passportIntroCard=$("passportIntroCard"),passportProgressCard=$("passportProgressCard"),passportProgressMessage=$("passportProgressMessage"),passportContinueBtn=$("passportContinueBtn"),questionCounter=$("questionCounter"),participantLabel=$("participantLabel"),quizProgressDots=$("quizProgressDots"),questionText=$("questionText"),answersContainer=$("answersContainer"),feedbackBox=$("feedbackBox"),feedbackIcon=$("feedbackIcon"),feedbackTitle=$("feedbackTitle"),feedbackExplanation=$("feedbackExplanation"),nextBtn=$("nextBtn"),stampTitle=$("stampTitle"),stampMessage=$("stampMessage"),stampContinueBtn=$("stampContinueBtn"),watchedBtn=$("watchedBtn"),openCameraBtn=$("openCameraBtn"),cameraError=$("cameraError"),cameraVideo=$("cameraVideo"),collectBtn=$("collectBtn"),veeButton=$("veeButton"),completionHeadline=$("completionHeadline"),finalPassportCard=$("finalPassportCard"),finalName=$("finalName"),finalTime=$("finalTime"),completionMessage=$("completionMessage");
const timerElements=[$("quizTimer"),$("stampTimer"),$("passportTimer"),$("videoTimer"),$("cameraIntroTimer"),$("cameraTimer")];
function showScreen(screen){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));screen.classList.add("active");window.scrollTo(0,0)}
function stampCount(){return Object.values(stamps).filter(Boolean).length}
function vibrateTiny(){if("vibrate" in navigator)navigator.vibrate(30)}
function formatSeconds(total){const m=Math.floor(total/60),s=total%60;return m+":"+String(s).padStart(2,"0")}
function getElapsedSeconds(){if(!challengeStartTime)return 0;const end=challengeEndTime||new Date();return Math.max(0,Math.floor((end-challengeStartTime)/1000))}
function updateTimerDisplays(){const txt="⏱ "+formatSeconds(getElapsedSeconds());timerElements.forEach(el=>{if(el)el.textContent=txt})}
function startChallengeTimer(){challengeStartTime=new Date();challengeEndTime=null;updateTimerDisplays();if(timerInterval)clearInterval(timerInterval);timerInterval=setInterval(updateTimerDisplays,1000)}
function stopChallengeTimer(){challengeEndTime=new Date();if(timerInterval){clearInterval(timerInterval);timerInterval=null}updateTimerDisplays()}
function renderPassport(container){const count=stampCount();container.innerHTML=`<div class="passport-title"><span>🛂 VEE Passport</span><span class="stamp-count">${count} / 3 Stamps</span></div><div class="stamp-grid">${renderStamp("quiz")}${renderStamp("video")}${renderStamp("vee")}</div>`}
function renderStamp(key){const earned=stamps[key];return `<div class="passport-stamp ${earned?"earned":""}"><div class="stamp-circle">${earned?"✓":""}</div><div class="stamp-label">${stampLabels[key]}</div></div>`}
function renderQuizProgressDots(){quizProgressDots.innerHTML=quiz.map((_,i)=>`<span class="quiz-dot ${i<=currentQuestion?"active":""}"></span>`).join("")}
function renderQuestion(){const q=quiz[currentQuestion];questionCounter.textContent="Question "+(currentQuestion+1)+" of "+quiz.length;questionText.textContent=q.question;answersContainer.innerHTML="";feedbackBox.classList.add("hidden");feedbackBox.classList.remove("correct","wrong");feedbackIcon.textContent="";feedbackTitle.textContent="";feedbackExplanation.textContent="";nextBtn.classList.add("hidden");renderQuizProgressDots();updateTimerDisplays();q.answers.forEach((answer,index)=>{const b=document.createElement("button");b.className="answer-btn";b.type="button";b.textContent=String.fromCharCode(97+index)+". "+answer;b.addEventListener("click",()=>handleAnswer(index));answersContainer.appendChild(b)})}
function handleAnswer(selectedIndex){const q=quiz[currentQuestion],buttons=document.querySelectorAll(".answer-btn"),isCorrect=selectedIndex===q.correct;if(isCorrect)correctCount++;buttons.forEach((button,index)=>{button.classList.add("disabled");if(index===q.correct){button.classList.add("correct");button.textContent="✓ "+button.textContent}if(index===selectedIndex&&selectedIndex!==q.correct){button.classList.add("wrong");button.textContent="✕ "+button.textContent}});feedbackBox.classList.remove("hidden");feedbackBox.classList.toggle("correct",isCorrect);feedbackBox.classList.toggle("wrong",!isCorrect);feedbackIcon.textContent=isCorrect?"✓":"✕";feedbackTitle.textContent=isCorrect?"Correct":"Not quite";feedbackExplanation.textContent=q.reveal;nextBtn.classList.remove("hidden")}
function showStampEarned(key,message,nextStep){stamps[key]=true;nextAfterStamp=nextStep;stampTitle.textContent=stampLabels[key]+" Stamp Earned!";stampMessage.textContent=message;vibrateTiny();updateTimerDisplays();showScreen(stampScreen)}
function showPassportProgress(message,nextStep){passportProgressMessage.textContent=message;passportContinueBtn.dataset.nextStep=nextStep;renderPassport(passportProgressCard);updateTimerDisplays();showScreen(passportProgressScreen)}
function openNextStep(step){if(step==="video"){updateTimerDisplays();showScreen(videoScreen);return}if(step==="camera"){updateTimerDisplays();showScreen(cameraIntroScreen);return}if(step==="complete")completeChallenge()}
function startCountdown(){const seq=["3","2","1","GO!" ];let i=0;countdownNumber.textContent=seq[i];countdownNumber.style.animation="none";countdownNumber.offsetHeight;countdownNumber.style.animation="";showScreen(countdownScreen);const t=setInterval(()=>{i++;if(i>=seq.length){clearInterval(t);startChallengeTimer();showScreen(quizScreen);renderQuestion();return}countdownNumber.textContent=seq[i];countdownNumber.style.animation="none";countdownNumber.offsetHeight;countdownNumber.style.animation=""},650)}
async function openNativeCamera(){openCameraBtn.disabled=true;openCameraBtn.textContent="Opening camera...";cameraError.textContent="";try{if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia)throw new Error("Camera is not supported by this browser.");cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}},audio:false});cameraVideo.srcObject=cameraStream;cameraVideo.setAttribute("playsinline","");cameraVideo.setAttribute("webkit-playsinline","");cameraVideo.muted=true;await cameraVideo.play();updateTimerDisplays();showScreen(cameraScreen)}catch(err){openCameraBtn.disabled=false;openCameraBtn.textContent="Open Camera";cameraError.textContent="Camera failed: "+err.message+". Try Safari, not Instagram/Telegram/LinkedIn in-app browser."}}
function stopCamera(){if(cameraStream){cameraStream.getTracks().forEach(track=>track.stop());cameraStream=null}}
function completeChallenge(){if(challengeCompleted)return;challengeCompleted=true;stopCamera();stopChallengeTimer();finalName.textContent=participantName;finalTime.textContent=formatSeconds(getElapsedSeconds());renderPassport(finalPassportCard);if(stampCount()===3){completionHeadline.textContent="VEE Passport Completed!";completionMessage.textContent="Show this screen to the facilitator. Fastest 5 participants with a completed VEE Passport win a prize."}else{completionHeadline.textContent=stampCount()+" / 3 Stamps Collected";completionMessage.textContent="Thanks for joining us! See you at the next Visa event."}showScreen(completeScreen)}
startBtn.addEventListener("click",()=>{participantName=participantInput.value.trim();if(participantName===""){nameError.textContent="Please enter your name.";participantInput.focus();return}nameError.textContent="";participantLabel.textContent=participantName;currentQuestion=0;correctCount=0;challengeStartTime=null;challengeEndTime=null;challengeCompleted=false;if(timerInterval){clearInterval(timerInterval);timerInterval=null}stamps.quiz=false;stamps.video=false;stamps.vee=false;openCameraBtn.disabled=false;openCameraBtn.textContent="Open Camera";cameraError.textContent="";renderPassport(passportIntroCard);showScreen(passportIntroScreen)});
participantInput.addEventListener("keydown",e=>{if(e.key==="Enter")startBtn.click()});
beginQuizBtn.addEventListener("click",startCountdown);
nextBtn.addEventListener("click",()=>{currentQuestion++;if(currentQuestion<quiz.length){renderQuestion();return}if(correctCount===quiz.length){showStampEarned("quiz","You answered all 5 questions correctly.","passportAfterQuiz")}else{showPassportProgress("Quiz completed. Your passport journey continues with the Video Stamp.","video")}});
stampContinueBtn.addEventListener("click",()=>{if(nextAfterStamp==="passportAfterQuiz"){showPassportProgress("Great start. Next, collect your Watch Video Stamp.","video");return}if(nextAfterStamp==="passportAfterVideo"){showPassportProgress("Almost there. Find VEE to collect your final stamp.","camera");return}if(nextAfterStamp==="complete")completeChallenge()});
passportContinueBtn.addEventListener("click",()=>openNextStep(passportContinueBtn.dataset.nextStep));
watchedBtn.addEventListener("click",()=>showStampEarned("video","Thanks for watching the video.","passportAfterVideo"));
openCameraBtn.addEventListener("click",openNativeCamera);
collectBtn.addEventListener("click",()=>showStampEarned("vee","You found VEE and collected your final stamp.","complete"));
veeButton.addEventListener("click",()=>showStampEarned("vee","You found VEE and collected your final stamp.","complete"));
