const quiz=[{question:"Q1. What makes consumers feel most rewarded today?",answers:["Earning more points","Bigger cashback percentages","Relevant offers at the right moment","Luxury reward catalogues"],correct:2,reveal:"Consumers increasingly value relevance and immediacy over accumulating rewards they'll redeem later. Loyalty is shifting from rewards programs to engagement ecosystems."},{question:"Q2. Which is hardest for issuers to build themselves?",answers:["Campaign reporting","Points management","A scaled merchant offer ecosystem","Customer communications"],correct:2,reveal:"Building and maintaining thousands of merchant relationships and offers at scale requires a large ecosystem and continuous content refresh."},{question:"Q3. Which statement is most likely to be true in 2030?",answers:["Points will disappear","Cashback will replace loyalty programs","Loyalty will become increasingly invisible and embedded","Consumers will join fewer programs"],correct:2,reveal:"Loyalty is evolving from standalone rewards programs to always-on engagement embedded across everyday experiences, moving from cost to a monetisation driver."}];

let participantName="",currentQuestion=0,startTime=null,cameraStream=null,challengeCompleted=false;
const homeScreen=document.getElementById("homeScreen"),quizScreen=document.getElementById("quizScreen"),cameraIntroScreen=document.getElementById("cameraIntroScreen"),cameraScreen=document.getElementById("cameraScreen"),completeScreen=document.getElementById("completeScreen"),startBtn=document.getElementById("startBtn"),participantInput=document.getElementById("participantName"),nameError=document.getElementById("nameError"),questionCounter=document.getElementById("questionCounter"),progressFill=document.getElementById("progressFill"),participantLabel=document.getElementById("participantLabel"),questionText=document.getElementById("questionText"),answersContainer=document.getElementById("answersContainer"),feedbackBox=document.getElementById("feedbackBox"),feedbackIcon=document.getElementById("feedbackIcon"),feedbackTitle=document.getElementById("feedbackTitle"),feedbackExplanation=document.getElementById("feedbackExplanation"),nextBtn=document.getElementById("nextBtn"),openCameraBtn=document.getElementById("openCameraBtn"),cameraError=document.getElementById("cameraError"),cameraVideo=document.getElementById("cameraVideo"),collectBtn=document.getElementById("collectBtn"),veeButton=document.getElementById("veeButton"),finalName=document.getElementById("finalName"),finalTime=document.getElementById("finalTime");

function showScreen(screen){document.querySelectorAll(".screen").forEach(item=>item.classList.remove("active"));screen.classList.add("active");window.scrollTo(0,0)}
function updateProgress(){progressFill.style.width=currentQuestion/quiz.length*100+"%"}
function renderQuestion(){const q=quiz[currentQuestion];questionCounter.textContent="Question "+(currentQuestion+1)+" of "+quiz.length;questionText.textContent=q.question;answersContainer.innerHTML="";feedbackBox.classList.add("hidden");feedbackBox.classList.remove("correct","wrong");feedbackIcon.textContent="";feedbackTitle.textContent="";feedbackExplanation.textContent="";nextBtn.classList.add("hidden");q.answers.forEach((answer,index)=>{const button=document.createElement("button");button.className="answer-btn";button.type="button";button.textContent=String.fromCharCode(97+index)+". "+answer;button.addEventListener("click",()=>handleAnswer(index));answersContainer.appendChild(button)})}
function handleAnswer(selectedIndex){const q=quiz[currentQuestion],buttons=document.querySelectorAll(".answer-btn"),isCorrect=selectedIndex===q.correct;buttons.forEach((button,index)=>{button.classList.add("disabled");if(index===q.correct){button.classList.add("correct");button.textContent="✓ "+button.textContent}if(index===selectedIndex&&selectedIndex!==q.correct){button.classList.add("wrong");button.textContent="✕ "+button.textContent}});feedbackBox.classList.remove("hidden");feedbackBox.classList.toggle("correct",isCorrect);feedbackBox.classList.toggle("wrong",!isCorrect);feedbackIcon.textContent=isCorrect?"✓":"✕";feedbackTitle.textContent=isCorrect?"Correct":"Not quite";feedbackExplanation.textContent=q.reveal;nextBtn.classList.remove("hidden")}
async function openNativeCamera(){openCameraBtn.disabled=true;openCameraBtn.textContent="Opening camera...";cameraError.textContent="";try{if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia){throw new Error("Camera is not supported by this browser.")}cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}},audio:false});cameraVideo.srcObject=cameraStream;cameraVideo.setAttribute("playsinline","");cameraVideo.setAttribute("webkit-playsinline","");cameraVideo.muted=true;await cameraVideo.play();showScreen(cameraScreen)}catch(err){openCameraBtn.disabled=false;openCameraBtn.textContent="Open Camera";cameraError.textContent="Camera failed: "+err.message+". Try Safari, not Instagram/Telegram/LinkedIn in-app browser."}}
function completeChallenge(){if(challengeCompleted)return;challengeCompleted=true;if(cameraStream){cameraStream.getTracks().forEach(track=>track.stop());cameraStream=null}const endTime=new Date(),totalSeconds=Math.max(0,Math.floor((endTime-startTime)/1000)),minutes=Math.floor(totalSeconds/60),seconds=totalSeconds%60;finalName.textContent=participantName;finalTime.textContent=minutes+":"+String(seconds).padStart(2,"0");showScreen(completeScreen)}
startBtn.addEventListener("click",()=>{participantName=participantInput.value.trim();if(participantName===""){nameError.textContent="Please enter your name.";participantInput.focus();return}nameError.textContent="";participantLabel.textContent=participantName;startTime=new Date();currentQuestion=0;challengeCompleted=false;showScreen(quizScreen);updateProgress();renderQuestion()});
participantInput.addEventListener("keydown",event=>{if(event.key==="Enter")startBtn.click()});
nextBtn.addEventListener("click",()=>{currentQuestion++;updateProgress();if(currentQuestion<quiz.length){renderQuestion();return}progressFill.style.width="100%";showScreen(cameraIntroScreen)});
openCameraBtn.addEventListener("click",openNativeCamera);
collectBtn.addEventListener("click",completeChallenge);
veeButton.addEventListener("click",completeChallenge);
