const quiz=[{question:"Q1. What makes consumers feel most rewarded today?",answers:["Earning more points","Bigger cashback percentages","Relevant offers at the right moment","Luxury reward catalogues"],correct:2,reveal:"Consumers increasingly value relevance and immediacy over accumulating rewards they'll redeem later. Loyalty is shifting from rewards programs to engagement ecosystems."},{question:"Q2. Which is hardest for issuers to build themselves?",answers:["Campaign reporting","Points management","A scaled merchant offer ecosystem","Customer communications"],correct:2,reveal:"Building and maintaining thousands of merchant relationships and offers at scale requires a large ecosystem and continuous content refresh."},{question:"Q3. Which statement is most likely to be true in 2030?",answers:["Points will disappear","Cashback will replace loyalty programs","Loyalty will become increasingly invisible and embedded","Consumers will join fewer programs"],correct:2,reveal:"Loyalty is evolving from standalone rewards programs to always-on engagement embedded across everyday experiences, moving from cost to a monetisation driver."}];

let participantName="",currentQuestion=0,startTime=null,arCreated=false,challengeCompleted=false;
const homeScreen=document.getElementById("homeScreen"),quizScreen=document.getElementById("quizScreen"),cameraIntroScreen=document.getElementById("cameraIntroScreen"),arScreen=document.getElementById("arScreen"),completeScreen=document.getElementById("completeScreen"),startBtn=document.getElementById("startBtn"),participantInput=document.getElementById("participantName"),nameError=document.getElementById("nameError"),questionCounter=document.getElementById("questionCounter"),progressFill=document.getElementById("progressFill"),participantLabel=document.getElementById("participantLabel"),questionText=document.getElementById("questionText"),answersContainer=document.getElementById("answersContainer"),feedbackBox=document.getElementById("feedbackBox"),feedbackIcon=document.getElementById("feedbackIcon"),feedbackTitle=document.getElementById("feedbackTitle"),feedbackExplanation=document.getElementById("feedbackExplanation"),nextBtn=document.getElementById("nextBtn"),openCameraBtn=document.getElementById("openCameraBtn"),collectPanel=document.getElementById("collectPanel"),collectBtn=document.getElementById("collectBtn"),arMount=document.getElementById("arMount"),finalName=document.getElementById("finalName"),finalTime=document.getElementById("finalTime");

function showScreen(screen){document.querySelectorAll(".screen").forEach(item=>item.classList.remove("active"));screen.classList.add("active");window.scrollTo(0,0)}
function updateProgress(){progressFill.style.width=currentQuestion/quiz.length*100+"%"}
function renderQuestion(){const q=quiz[currentQuestion];questionCounter.textContent="Question "+(currentQuestion+1)+" of "+quiz.length;questionText.textContent=q.question;answersContainer.innerHTML="";feedbackBox.classList.add("hidden");feedbackBox.classList.remove("correct","wrong");feedbackIcon.textContent="";feedbackTitle.textContent="";feedbackExplanation.textContent="";nextBtn.classList.add("hidden");q.answers.forEach((answer,index)=>{const button=document.createElement("button");button.className="answer-btn";button.type="button";button.textContent=String.fromCharCode(97+index)+". "+answer;button.addEventListener("click",()=>handleAnswer(index));answersContainer.appendChild(button)})}
function handleAnswer(selectedIndex){const q=quiz[currentQuestion],answerButtons=document.querySelectorAll(".answer-btn"),isCorrect=selectedIndex===q.correct;answerButtons.forEach((button,index)=>{button.classList.add("disabled");if(index===q.correct){button.classList.add("correct");button.textContent="✓ "+button.textContent}if(index===selectedIndex&&selectedIndex!==q.correct){button.classList.add("wrong");button.textContent="✕ "+button.textContent}});feedbackBox.classList.remove("hidden");feedbackBox.classList.toggle("correct",isCorrect);feedbackBox.classList.toggle("wrong",!isCorrect);feedbackIcon.textContent=isCorrect?"✓":"✕";feedbackTitle.textContent=isCorrect?"Correct":"Not quite";feedbackExplanation.textContent=q.reveal;nextBtn.classList.remove("hidden")}

function createArScene(){if(arCreated)return;arCreated=true;arMount.innerHTML=`<a-scene id="arScene" embedded vr-mode-ui="enabled: false" renderer="logarithmicDepthBuffer: true; alpha: true" arjs="sourceType: webcam; debugUIEnabled: false; trackingMethod: best;"><a-assets><img id="veeTexture" src="vee.gif"></a-assets><a-marker id="hiroMarker" preset="hiro"><a-plane id="veeObject" src="#veeTexture" position="0 0.05 0" rotation="-90 0 0" width="1.4" height="1.4" transparent="true" material="transparent: true; alphaTest: 0.1;"></a-plane></a-marker><a-entity camera cursor="rayOrigin: mouse"></a-entity></a-scene>`;const marker=document.getElementById("hiroMarker"),vee=document.getElementById("veeObject");marker.addEventListener("markerFound",()=>collectPanel.classList.remove("hidden"));marker.addEventListener("markerLost",()=>{if(!challengeCompleted)collectPanel.classList.add("hidden")});vee.addEventListener("click",completeChallenge)}
async function requestCameraThenOpenAR(){openCameraBtn.disabled=true;openCameraBtn.textContent="Opening camera...";try{if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia)throw new Error("Camera not supported");const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}},audio:false});stream.getTracks().forEach(track=>track.stop());collectPanel.classList.add("hidden");showScreen(arScreen);setTimeout(createArScene,250)}catch(error){openCameraBtn.disabled=false;openCameraBtn.textContent="Open Camera";alert("Camera could not be opened. Please allow camera permission and use the GitHub Pages HTTPS link on your phone.")}}
function completeChallenge(){if(challengeCompleted)return;challengeCompleted=true;const endTime=new Date(),totalSeconds=Math.max(0,Math.floor((endTime-startTime)/1000)),minutes=Math.floor(totalSeconds/60),seconds=totalSeconds%60;finalName.textContent=participantName;finalTime.textContent=minutes+":"+String(seconds).padStart(2,"0");showScreen(completeScreen)}
startBtn.addEventListener("click",()=>{participantName=participantInput.value.trim();if(participantName===""){nameError.textContent="Please enter your name.";participantInput.focus();return}nameError.textContent="";participantLabel.textContent=participantName;startTime=new Date();currentQuestion=0;challengeCompleted=false;showScreen(quizScreen);updateProgress();renderQuestion()});
participantInput.addEventListener("keydown",event=>{if(event.key==="Enter")startBtn.click()});
nextBtn.addEventListener("click",()=>{currentQuestion++;updateProgress();if(currentQuestion<quiz.length){renderQuestion();return}progressFill.style.width="100%";showScreen(cameraIntroScreen)});
openCameraBtn.addEventListener("click",requestCameraThenOpenAR);
collectBtn.addEventListener("click",completeChallenge);
